import Head from 'next/head'
import styles from '../styles/h2fg2.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Typewriter Text</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.typewriter}>
          <p>
            There is a theory which states that if ever anyone discovers exactly
            what the Universe is for and why it is here, it will instantly
            disappear and be replaced by something even more bizarre and
            inexplicable. There is another theory which states that this has
            already happened.
          </p>
          <p>- Douglas Adams</p>
        </div>
      </main>
    </div>
  )
}
